[package]
name = "mantis"
version = "0.1.0"
authors = ["theredfish <did.julian@gmail.com>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14.7", features = ["client", "http1", "http2", "runtime"] }
serde = "1.0.125"
serde_json = "1.0.64"
http = "0.2.4"
url = "2.2.2"
futures = "0.3"

[dev-dependencies]
tokio-test = "0.4.1"
tokio = { version = "1.12", features = ["macros"] }
reqwest = { version = "0.11.4", features = ["json"] }
httpmock = "0.6.2"
